@baseUrl = http://localhost:5000/api/v1

POST {{baseUrl}}/advertisement/
Content-Type: application/json

{
    "header": "Заметка",
    "description": "Важная",
    "user_id": 1
}


POST {{baseUrl}}/advertisement/
Content-Type: application/json

{
    "header": "Заметочка",
    "description": "Крайне важная",
    "user_id": 2
}