@baseUrl = http://localhost:5000/api/v1

POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "<EMAIL1>",
    "password": "<PASSWORD1>"
}

###

POST {{baseUrl}}/logout/

###

POST {{baseUrl}}/advertisement/
Content-Type: application/json

{
    "header": "Заметка",
    "description": "Важная"
}

###

POST {{baseUrl}}/advertisement/
Content-Type: application/json

{
    "header": "Заметочка",
    "description": "Крайне важная"
}

###

DELETE {{baseUrl}}/advertisement/1
Content-Type: application/json

###

PATCH {{baseUrl}}/advertisement/3
Content-Type: application/json

{
    "description": "Ну очень важная"
}

###

GET {{baseUrl}}/advertisement/2

###

POST {{baseUrl}}/login/
Content-Type: application/json

{
    "email": "<EMAIL2>",
    "password": "<PASSWORD2>"
}

###